name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Windows App
        run: |
          docker build -t robotics-contributors-win -f Dockerfile.windows .
          docker run --rm -v ${{ github.workspace }}/out:/app/out robotics-contributors-win

      - name: Build macOS App
        run: |
          docker build -t robotics-contributors-mac -f Dockerfile.macos .
          docker run --rm -v ${{ github.workspace }}/out:/app/out robotics-contributors-mac

      - name: Build Linux App
        run: |
          docker build -t robotics-contributors-linux -f Dockerfile.linux .
          docker run --rm -v ${{ github.workspace }}/out:/app/out robotics-contributors-linux

      - name: List Output Directory (Debug)
        run: find out -type f | sort

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: robotics-contributors-windows
          path: out/make/squirrel.windows/x64/

      - name: Upload macOS Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: robotics-contributors-mac
          path: out/make/zip/darwin/x64/

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: robotics-contributors-linux
          path: out/make/deb/x64/

      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: v${{ env.VERSION }}
      #     name: Release v${{ env.VERSION }}
      #     body: "Automated release of robotics-contributors v${{ env.VERSION }}"
      #     draft: false
      #     prerelease: false
      #     files: out/make/**
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}