name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Make Electron App (Mac)
        run: npm run make -- --platform=darwin

      - name: Upload Mac Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: robotics-contributors-mac
          path: out/make/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Make Electron App (Windows)
        run: npm run make -- --platform=win32

      - name: List Output Directory (Debug)
        run: dir "out\make\" /s

      - name: Upload Windows Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: robotics-contributors-windows
          path: out/make/

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Required Dependencies for Linux
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libnss3 libasound2t64 libxss1 libgbm1 libxshmfence1 libegl1

      - name: Make Electron App (Linux)
        run: npm run make -- --platform=linux

      - name: List Output Directory (Debug)
        run: find out/make -type f | sort

      - name: Upload Linux Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: robotics-contributors-linux
          path: out/make/

      # - name: Create GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     tag_name: v${{ env.VERSION }}
      #     name: Release v${{ env.VERSION }}
      #     body: "Automated release of robotics-contributors v${{ env.VERSION }}"
      #     draft: false
      #     prerelease: false
      #     files: out/make/**
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
